package io.github.keemgdeok.metadq.core;

public enum ReasonCode {
  ACTIVE_DELETE_FILES,
  EMPTY_TABLE,
  MISSING_COLUMN,
  MISSING_METRICS,
  INCONSISTENT_METRICS,
  NO_CURRENT_SNAPSHOT,
  TYPE_MISMATCH,
  UNSUPPORTED_COLUMN_TYPE,
  UNSUPPORTED_FORMAT_VERSION,
  INVALID_RULE,
  CATALOG_ERROR
}
